/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MainClasses.User;
import java.awt.Desktop;
import java.io.File;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Rafly
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    User user;
    private static final  Desktop desk = Desktop.getDesktop();
    public AboutUs() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public AboutUs(User user)   { 
          initComponents();
          this.user = user;
        this.setLocationRelativeTo(null);
               String path = "src/Assets";
      File tempatTujuan = new File(path + "/" + "Logo_Jadi.png" );
      ImageIcon icon = new ImageIcon(tempatTujuan.getPath());
      this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rafly = new javax.swing.JLabel();
        farhan = new javax.swing.JLabel();
        apis = new javax.swing.JLabel();
        labelx = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 535));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rafly.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rafly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raflyMouseClicked(evt);
            }
        });
        jPanel1.add(rafly, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 230, 160));

        farhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        farhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farhanMouseClicked(evt);
            }
        });
        jPanel1.add(farhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 230, 160));

        apis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apisMouseClicked(evt);
            }
        });
        jPanel1.add(apis, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 220, 160));

        labelx.setBackground(new java.awt.Color(255, 153, 0));
        labelx.setFont(new java.awt.Font("InputMono Medium", 0, 18)); // NOI18N
        labelx.setForeground(new java.awt.Color(255, 255, 255));
        labelx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelx.setText("Back");
        labelx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelx.setOpaque(true);
        labelx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelxMouseClicked(evt);
            }
        });
        jPanel1.add(labelx, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 100, 40));

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/AboutUSBG_Jadi.png"))); // NOI18N
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMouseClicked(evt);
            }
        });
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raflyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raflyMouseClicked
        // TODO add your handling code here:
        //Panggil Class Desktop agar java dapat menjalankan Aplikasi terkait yang teregistrasi
        //dalam Native Desktop 
        // Lalu Tangkap URI nya(Uniform Resource Identifier)
      
       
        try {
            desk.browse(new URI("https://www.instagram.com/raflyafrzl/"));
        } catch (Exception ex) {
            Logger.getLogger(AboutUs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_raflyMouseClicked

    private void labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_labelMouseClicked

    private void farhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farhanMouseClicked
        // TODO add your handling code here:
           try {
            desk.browse(new URI("https://www.instagram.com/al_anzharii/"));
        } catch (Exception ex) {
            Logger.getLogger(AboutUs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_farhanMouseClicked

    private void labelxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelxMouseClicked
        // TODO add your handling code here:
        if(this.user != null) { 
              Dashboard dash = new Dashboard(user);
        dash.setVisible(true);
        this.setVisible(false);
        this.dispose();
        }else { 
              Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.setVisible(false);
        this.dispose();
        }
    }//GEN-LAST:event_labelxMouseClicked

    private void apisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apisMouseClicked
        // TODO add your handling code here:
              try {
            desk.browse(new URI("https://www.instagram.com/hafidzph/"));
        } catch (Exception ex) {
            Logger.getLogger(AboutUs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_apisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apis;
    private javax.swing.JLabel farhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelx;
    private javax.swing.JLabel rafly;
    // End of variables declaration//GEN-END:variables
}
