/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Connection.Conn;
import MainClasses.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafly
 */
public class ChangeData extends javax.swing.JFrame {
    Conn con;
    User user;
    /**
     * Creates new form ChangeData
     */
    public ChangeData() {
        Conn.koneksi();
        this.con = new Conn();
        initComponents();
    }
    
    public ChangeData(String name, String email, String password, String gender) { 
        Conn.koneksi();
        this.con = new Conn();
        initComponents();
        user = new User();
        this.setTitle("Ubah Data");
        if(gender.equals("laki-laki")){
            lakiNew.setSelected(true);
        }else{
            peremNew.setSelected(true);
        }
        username.setText(name);
        email1.setText(email);
        pass.setText(password);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        lakiNew = new javax.swing.JRadioButton();
        peremNew = new javax.swing.JRadioButton();
        pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Change_Jadi.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 100, 40));

        username.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        username.setBorder(null);
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 240, 30));

        email1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        email1.setBorder(null);
        jPanel3.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 240, 27));

        group.add(lakiNew);
        lakiNew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lakiNew.setText("Laki-laki");
        lakiNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiNewActionPerformed(evt);
            }
        });
        jPanel3.add(lakiNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 110, -1));

        group.add(peremNew);
        peremNew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        peremNew.setText("Perempuan");
        peremNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peremNewActionPerformed(evt);
            }
        });
        jPanel3.add(peremNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 110, -1));

        pass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pass.setBorder(null);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 240, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/ChangeDataBG_Jadi.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 710, 500));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void peremNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peremNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peremNewActionPerformed

    private void lakiNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiNewActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        String newUser = username.getText();
        String newEmail = email1.getText();
        String newPass = pass.getText();
        String gender = "";
        if(lakiNew.isSelected()){
            gender = "laki-laki";
        }else{
            gender = "perempuan";
        }
        String query = "UPDATE `user` SET username='"+newUser+"', email='"+newEmail+"', password='"+newPass+"', gender='"+gender+"' WHERE username='"+newUser+"' OR email='"+newEmail+"' OR password='"+newPass+"' AND TRUE";
        try {
            con.getStm().executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            User user = new User();
            user.setName(newUser);
            user.setEmail(newEmail);
            user.setPassword(newPass);
            user.setGender(gender);
            Dashboard ds = new Dashboard(user);
            ds.setVisible(true);
            this.setVisible(false);
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(ChangeData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked
    private String name;
    private String email;
    private String password;
    private String gender;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email1;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton lakiNew;
    private javax.swing.JPasswordField pass;
    private javax.swing.JRadioButton peremNew;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
