/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection.Conn;
import MainClasses.Drink;
import MainClasses.Food;
import MainClasses.Ticket;
import MainClasses.User;
import javax.swing.JOptionPane;

/**
 *
 * @author apit
 */
public class FoodOrder extends javax.swing.JFrame {
User user;
Food food;
Conn con;
Drink drink;
Ticket ticket;
    /**
     * Creates new form FoodOrder
     */
    public FoodOrder() {
        initComponents();
        this.con = new Conn();
        this.setLocationRelativeTo(null);
    }
     public FoodOrder(User user, Ticket ticket, Food food, Drink drink){
       initComponents();
       this.con = new Conn();
       this.user = user;
       this.ticket = ticket;
       this.drink = drink;
       this.food = food;
       this.setTitle("Order Makanan");
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        makanan = new javax.swing.JComboBox<>();
        rasa = new javax.swing.JComboBox<>();
        ukuran = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Submit_JadiPanjang.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Back_Jadi.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 140, 110));

        makanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Popcorn" }));
        getContentPane().add(makanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 100, -1));

        rasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caramel", "Cheese", "Butter" }));
        getContentPane().add(rasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 90, -1));

        ukuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Large", "Medium", "Small" }));
        getContentPane().add(ukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 80, -1));

        jumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/FoodMenu_Jadi.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
             String name = makanan.getSelectedItem().toString();
        String sz = ukuran.getSelectedItem().toString();
        String flav = rasa.getSelectedItem().toString();
        int value = Integer.parseInt(jumlah.getSelectedItem().toString());
        if(sz.equalsIgnoreCase("Large") && value >=3){
            this.food = new Food(name, "30000", 0.20, flav, value, sz);
        }else if(sz.equalsIgnoreCase("Medium") && value >=3){
          this.food = new Food(name, "23000", 0.15, flav, value, sz);
        }else if(sz.equalsIgnoreCase("Small") && value >=3){
           this.food = new Food(name, "16000", 0.10, flav, value, sz);
        }else{
            if(sz.equalsIgnoreCase("Large")){
            this.food = new Food(name, "30000", 0.0, flav, value, sz);
             }else if(sz.equalsIgnoreCase("Medium")){
                 this.food = new Food(name, "23000", 0.0, flav, value, sz);
             }else { 
                  this.food = new Food(name, "16000", 0.0, flav, value, sz);
             }
            
           
        }
        JOptionPane.showMessageDialog(null, "Berhasil memesanan silahkan checkout");
        Dashboard ds = new Dashboard(user, ticket, food, drink);
        ds.setVisible(true);
       this.setVisible(false);
       this.dispose();
    
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Dashboard dash = new Dashboard(user, ticket, food, drink);
        dash.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jumlah;
    private javax.swing.JComboBox<String> makanan;
    private javax.swing.JComboBox<String> rasa;
    private javax.swing.JComboBox<String> ukuran;
    // End of variables declaration//GEN-END:variables
}
