/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection.Conn;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import MainClasses.Movies;
/**
 *
 * @author Rafly
 */
public class InsertMovies extends javax.swing.JFrame {
        private final String GENERATE = "ABCEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    private String filename = null; 
    private JFileChooser chooser  = null;
     private File file = null;
    private ImageIcon icon = null;
    private Image img = null;
    private String n  = null;
    String[] splitPath = null;
    Conn con;
    Movies movies;
    /**
     * Creates new form UpdateMovies
     */
    public InsertMovies() {
        this.con= new Conn();
        initComponents();
        code.setEditable(false);
       movies = new Movies();
        this.setLocationRelativeTo(null);
        this.setTitle("Input Movie");
                    String path = "src/Assets";
      File tempatTujuan = new File(path + "/" + "Logo_Jadi.png" );
      ImageIcon icon = new ImageIcon(tempatTujuan.getPath());
      this.setIconImage(icon.getImage());
       
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        moviesName = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        gambar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sinopsis = new javax.swing.JTextArea();
        tRelease1 = new javax.swing.JComboBox<>();
        tRelease2 = new javax.swing.JComboBox<>();
        trailer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Back_Jadi.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 110, 120));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Upload_Jadi.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 110, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Insert_Jadi.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 110, 30));

        moviesName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        moviesName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(moviesName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 40));

        price.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priceMouseClicked(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 40));

        code.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        code.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        jPanel1.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 40));

        gambar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel1.add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 210, 320));

        sinopsis.setColumns(20);
        sinopsis.setRows(5);
        sinopsis.setBorder(null);
        jScrollPane1.setViewportView(sinopsis);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 180, 110));

        tRelease1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel1.add(tRelease1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 100, 30));

        tRelease2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel1.add(tRelease2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 30));

        trailer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        trailer.setBorder(null);
        trailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trailerActionPerformed(evt);
            }
        });
        jPanel1.add(trailer, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 300, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/UpdateMoviesA_Jadi.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 790, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceMouseClicked
        // TODO add your handling code here:
              String temp ="";
              
        //generate CodeMovie 
            if(!(moviesName.getText().equals(""))) { 
              if(moviesName.getText().length() > 3) { 
                temp += moviesName.getText().substring(0,3) +  "-"; 
              }else { 
                temp += moviesName.getText();
              }
              for(int i = 0; i < 3; i++) { 
                   int random = (int)Math.floor(Math.random() * (9 - 1 + 0) + 0);
                   temp+= random;
              }
         code.setText(temp);
            }else { 
                  JOptionPane.showMessageDialog(null, "Tolong Masukan nama movie", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
       
        
    }//GEN-LAST:event_priceMouseClicked

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
          try { 
        chooser  = new JFileChooser(); 
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        filename = file.getAbsolutePath();
       
         icon = new ImageIcon(filename);
         img = icon.getImage().getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
        icon  = new ImageIcon(img);
         n = filename.replace("\\", "/");
         splitPath = n.split("/");
       
        gambar.setIcon(icon);
        }catch(Exception e) { 
            JOptionPane.showMessageDialog(null,"Tidak Memasukan apapun" , "Warning!" , JOptionPane.WARNING_MESSAGE );
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         String pathFolder = "src/MoviesImages";
        File directory = new File(pathFolder);
        if(!directory.exists()) { 
            directory.mkdirs();
        }
        File srcFile = null; 
        File tempatTujuan = null; 
        String ekstensiGambar = filename.substring(filename.lastIndexOf('.')+1);
        srcFile = new File(filename);
        String hasil = "";
             for(int i = 0; i <=4; i++) { 
          int random = (int)Math.floor(Math.random() * (GENERATE.length()-1- 1 + 1) + 1);
            hasil += GENERATE.charAt(random);
      } 
      System.out.println(hasil);
       
        tempatTujuan  = new File(pathFolder + "/" + hasil +"."+ ekstensiGambar);
        ///NamaGambar masukin ke DB
        String namaGambar = hasil+ "." + ekstensiGambar;
            try {
                Files.copy(srcFile.toPath(), tempatTujuan.toPath());
            } catch (IOException ex) {
                Logger.getLogger(InsertMovies.class.getName()).log(Level.SEVERE, null, ex);
            }
        String movie = moviesName.getText();
        String harga = price.getText();
        String kode = code.getText();
        String tahun = tRelease2.getSelectedItem().toString() + "-" + tRelease1.getSelectedItem().toString() + "-2022";
        String sinop = sinopsis.getText();
        String sTrailer = trailer.getText();
//        String query = "INSERT INTO `movies`(namaMovie`, `harga`, `code`, `tahun`, `sinopsis`, `namaFile`) VALUES ('"+movie+"','"+harga+"','"+kode+"','"+tahun+"','"+sinop+"','"+namaGambar+"')";
          String query = "INSERT INTO `movies` (namaMovie, harga, code, tahun, sinopsis, namaFile, trailer) VALUES ('"+movie+"','"+harga+"','"+kode+"', '"+tahun+"', '"+sinop+"', '"+namaGambar+"' , '"+sTrailer+"' )";

        
            try {
                con.getStm().executeUpdate(query);
                   JOptionPane.showMessageDialog(null, "Data berhasil diupload");
                    movies.setHarga(harga);
                movies.setKode(kode);
                movies.setTahun(tahun);
                movies.setSinopsis(sinop);
                movies.setNama(movie);
                movies.setNamaFile(namaGambar);
                movies.setTrailer(sTrailer);
                Dashboard dash = new Dashboard(movies);
                dash.setVisible(true);
                this.setVisible(false);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(InsertMovies.class.getName()).log(Level.SEVERE, null, ex);
            }
             
                
                 //
               
           
    }//GEN-LAST:event_jLabel2MouseClicked

    private void trailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trailerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trailerActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moviesName;
    private javax.swing.JTextField price;
    private javax.swing.JTextArea sinopsis;
    private javax.swing.JComboBox<String> tRelease1;
    private javax.swing.JComboBox<String> tRelease2;
    private javax.swing.JTextField trailer;
    // End of variables declaration//GEN-END:variables
}
