/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GUI;
import Connection.Conn;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import InterfaceData.Validate;
import javax.swing.JFrame;
import GUI.Register;
import java.io.File;
import javax.swing.ImageIcon;
/**
 *
 * @author Rafly
 */
public class Register extends javax.swing.JFrame implements Validate {
    int role = 2;
    /**
     * Creates new form Register
     */
    Conn con; 
    public Register() {
        initComponents();   
        this.con = new Conn(); 
        this.setLocationRelativeTo(null);
        this.setTitle("Halaman Register");
            String path = "src/Assets";
      File tempatTujuan = new File(path + "/" + "Logo_Jadi.png" );
      ImageIcon icon = new ImageIcon(tempatTujuan.getPath());
      this.setIconImage(icon.getImage());
    }
    
    
  
     //true and false 
    //false and true
    //false and false
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        perem = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        kpassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        checkbox = new javax.swing.JCheckBox();
        email = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        perempuan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/HaveAnAccount_Jadi.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 190, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 110, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        buttonGroup1.add(perem);
        perem.setFont(new java.awt.Font("JetBrains Mono", 1, 15)); // NOI18N
        perem.setForeground(new java.awt.Color(0, 0, 0));
        perem.setText("Perempuan");
        jPanel1.add(perem, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, 30));

        buttonGroup1.add(laki);
        laki.setFont(new java.awt.Font("JetBrains Mono", 1, 15)); // NOI18N
        laki.setForeground(new java.awt.Color(0, 0, 0));
        laki.setText("Laki-Laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        jPanel1.add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 120, 30));

        username.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        username.setBorder(null);
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 246, 40));

        jButton1.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Submit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 100, 30));

        kpassword.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        kpassword.setBorder(null);
        jPanel1.add(kpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 250, 36));

        password.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 250, 50));

        checkbox.setBackground(new java.awt.Color(255, 255, 255));
        checkbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkbox.setForeground(new java.awt.Color(255, 255, 255));
        checkbox.setText("Show Password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 118, -1));

        email.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        email.setBorder(null);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 241, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Admin.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 100, 30));

        perempuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Register_Jadi.png"))); // NOI18N
        jPanel1.add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        
        String getUser = username.getText();
        String getPass = password.getText(); 
        String konPassword = kpassword.getText();
        String emailData = email.getText();
        String gender = "";
        
        if(laki.isSelected()) { 
            gender = "laki-laki";
        }else if(perem.isSelected()) { 
            gender = "perempuan";
        }
        
        String queryCheck = "SELECT * FROM `user` WHERE username = '"+getUser+"' OR email = '"+emailData+"';";
        
        if(getPass.length() >=6){ 
            //Call Static Method for every Users who wanted to register, and check it 
            // is email valid? or not
            if(Validate.isValid(emailData)) { 
              try {
              con.setRs(con.getStm().executeQuery(queryCheck));
                if(con.getRs().next()) {
                String emailDb  = con.getRs().getString("email"); 
                String userDb = con.getRs().getString("username");
                if(emailDb.equals(emailData)) { 
                    JOptionPane.showMessageDialog(null, "Email sudah terdaftar", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
                }else if(userDb.equals(getUser)) { 
                JOptionPane.showMessageDialog(null, "Username sudah terdaftar", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
                }
            }else if(getPass.equals("")) {     
                 JOptionPane.showMessageDialog(null, "Password Tidak boleh kosong", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
            }else if(!(laki.isSelected() || perem.isSelected())) {  
                JOptionPane.showMessageDialog(null, "Gender Tidak boleh kosong", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
            }
            else {
              if(getPass.equals(konPassword)) { 
                String query = "INSERT INTO `user` (username, password, email, gender) VALUES ('"+getUser+"','"+getPass+"','"+emailData+"', '"+gender+"');";
                //Insert Data 
                con.getStm().executeUpdate(query);
               JOptionPane.showMessageDialog(null, "Data Berhasil ditambahkan", "Registrasi Sukses", JOptionPane.INFORMATION_MESSAGE);
               username.setText("");
               password.setText("");
               kpassword.setText("");
               email.setText("");
               Login log = new Login(); 
               log.setVisible(true);
               this.setVisible(false);
               this.dispose();
              }else { 
                JOptionPane.showMessageDialog(null, "Password Tidak sesuai", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
              }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
            }else { 
               JOptionPane.showMessageDialog(null, "Email Tidak Valid", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE); 
            }
       }else { 
            JOptionPane.showMessageDialog(null, "Panjang Password Harus lebih dari 5 karakter", "Registrasi Gagal", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public  void setEnableThisFrame() { 
       
       this.setVisible(false);
       InputAdmin admin = new InputAdmin(); 
       admin.setVisible(true);
       this.dispose();
        
    }
    
    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:
         if(checkbox.isSelected()) { 
           password.setEchoChar((char)0);
          
         }else { 
          password.setEchoChar('*');
         }
        
    }//GEN-LAST:event_checkboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setEnableThisFrame();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField kpassword;
    private javax.swing.JRadioButton laki;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton perem;
    private javax.swing.JLabel perempuan;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables


//    public static boolean isValid(String email) {
// 
//    }
//    
   
}
